import fs from 'fs-extra';
import path from 'path';
import {
	getLibrarySourceFiles,
	logger,
	type TLibrarySourceOptions,
} from '../utils.ts';


export type TCreateIndexFileOptions = TLibrarySourceOptions;

type TCollectedExports = {
	valueExports: string[];
	isRequired?: boolean;
};

function buildIndexModuleExport(
	relativePath: string,
	moduleExports: TCollectedExports,
	usedExportNames: Set<string>,
): { imports: string[]; exports: string[] } {
	const importLines: string[] = [];
	const exportLines: string[] = [];
	const valueExports = moduleExports.valueExports.filter(exportName => {
		if (usedExportNames.has(exportName)) {
			return false;
		}

		usedExportNames.add(exportName);
		return true;
	});

	if (valueExports.length > 0) {
		exportLines.push(
			`export { ${valueExports.join(', ')} } from './${relativePath}';`,
		);
	} else if (moduleExports.isRequired) {
		importLines.push(`import './${relativePath}';`);
	}

	return { imports: importLines, exports: exportLines };
}


export function createIndexFile(
	srcDir: string,
	options: TCreateIndexFileOptions = {},
) {
	const filePaths = getLibrarySourceFiles(srcDir, options);

	if (filePaths.length === 0) {
		logger.info('[IndexPlugin] Nenhum arquivo .ts encontrado para importar.');
		return;
	}
	const usedExportNames = new Set<string>();
	const importLines: string[] = [];
	const exportLines: string[] = [];

	logger.info(`[IndexPlugin] Gerando index.ts com ${filePaths.length} arquivos...`);

	let index: string = `// Generated by createIndexFile.\n\n`;

	filePaths.forEach(filePath => {
		const relativePath = filePath.relativePath;
		const moduleExports = {
			valueExports: filePath.valueExports,
			isRequired: filePath.isRequired,
		};
		const fileLines = buildIndexModuleExport(
			relativePath,
			moduleExports,
			usedExportNames,
		);

		if (fileLines.imports.length === 0 && fileLines.exports.length === 0) {
			return;
		}

		importLines.push(...fileLines.imports);
		exportLines.push(...fileLines.exports);
	});

	if (importLines.length > 0) {
		index += `${importLines.join('\n')}\n`;
		if (exportLines.length > 0) {
			index += `\n`;
		}
	}

	if (exportLines.length > 0) {
		index += `${exportLines.join('\n')}\n`;
	}

	fs.outputFileSync(path.join(srcDir, 'index.ts'), index);
	logger.success('[IndexPlugin] index.ts gerado com sucesso!');
}
