import fs from 'fs-extra';
import path from 'path';
import type { PluginOption } from "vite";

/**
 * Cria um plugin Vite para gerar um arquivo index.d.ts que importa todas as definições de tipo.
 * @returns {import('vite').Plugin}
 */
export function indexPlugin(desiredOutDirs?: string[]): PluginOption {
	let compiledOutputPath: string;
	let outDirs: string[];


  return {
    name: 'vite-plugin-index',

    /**
     * Obtém as configurações de output do Rollup para determinar o diretório de saída.
     * @param {import('vite').ResolvedConfig} config
     */
    configResolved(config) {
      compiledOutputPath = config.build.outDir || 'dist';
			outDirs = desiredOutDirs || [compiledOutputPath];
    },

    /**
     * Hook executado após o Rollup ter concluído a criação do bundle.
     */
    async closeBundle() {
			const filePaths = fs
				.globSync(`${compiledOutputPath}/**/*.d.ts`);
			outDirs.forEach(async (outDir) => {
				try {
					if (filePaths.length === 0) {
						console.log('[index] Nenhum arquivo .d.ts encontrado para importar.');
						return;
					}

					let index: string = `// Generated by IndexPlugin.\n\n`;
					let indexdts: string = `// Generated by IndexPlugin.\n\n`;

					filePaths.forEach(filePath => {
						let relativePath = path.relative(outDir, filePath);
						relativePath = relativePath.replace(/\.d\.ts$/, '');
						relativePath = relativePath.replace(/\\/g, '/');
						index += `export * from './${relativePath}.js';\n`;
						indexdts += `export * from './${relativePath}.js';\n`;
					});

					await fs.outputFile(path.join(outDir, 'index.d.ts'), indexdts);
					await fs.outputFile(path.join(outDir, 'index.js'), index);
				} catch (error) {
					console.error('[index] Erro ao criar o index.d.ts:', error);
				}
			});
    },
  };
}
