import fs from 'fs-extra';
import path from 'path';
import type { PluginOption } from "vite";

/**
 * Cria um plugin Vite para gerar um arquivo index.d.ts que importa todas as definições de tipo.
 * @returns {import('vite').Plugin}
 */
export default function IndexPlugin(): PluginOption {
  let outDir: string;

  return {
    name: 'vite-plugin-index',

    /**
     * Obtém as configurações de output do Rollup para determinar o diretório de saída.
     * @param {import('vite').ResolvedConfig} config
     */
    configResolved(config) {
      const rollupOutput = Array.isArray(config.build.rollupOptions.output)
        ? config.build.rollupOptions.output[0]
        : config.build.rollupOptions.output;

      outDir = rollupOutput?.dir || config.build.outDir || 'dist';
    },

    /**
     * Hook executado após o Rollup ter concluído a criação do bundle.
     */
    async closeBundle() {
      if (!outDir) {
        console.error('[index] Não foi possível determinar o diretório de saída (outDir). Operação abortada.');
        return;
      }

      try {
        const filePaths = fs.globSync(path.join(outDir, '**/*.d.ts'), {});

        if (filePaths.length === 0) {
          console.log('[index] Nenhum arquivo .d.ts encontrado para importar.');
          return;
        }

        let importsContent = `// Generated by IndexPlugin.\n\n`;
        filePaths.forEach(filePath => {
          let relativePath = path.relative(outDir, filePath);
          relativePath = relativePath.replace(/\.d\.ts$/, '');
          relativePath = relativePath.replace(/\\/g, '/');
          importsContent += `export * from './${relativePath}';\n`;
        });

        await fs.outputFile(path.join(outDir, 'index.d.ts'), importsContent);
        await fs.outputFile(path.join(outDir, 'index.js'), importsContent);
      } catch (error) {
        console.error('[index] Erro ao criar o index.d.ts:', error);
      }
    },
  };
}
